from __future__ import print_function, division

def compile_target(target, clean=False, silent=False):
    '''\
    :py:func:`compile_target` is a function to call make for a specific
    target from within python code. :py:func:`compile_target` assumes
    that it is being called in the directory containing the Makefile.
 
    :argument target:
        The target to make for.  If left empty ('') then it will make all.
    :type target: str
    :keyword silent:
        By default, :py:func:`compile_target` is not silent and will
        display all output generated by make.  If *silent* is set to
        :py:const:`True`, output will be suppressed.
    :type silent: bool, optional
    :rtype: None
    :exception:
        :py:exc:`ImportError`: The target cannot be compiled.
    '''
    from subprocess import call
    from os import devnull

    if clean:
        command = ['make clean', target]
        if silent:
            with open(devnull, 'w') as dev_null:
                retcode = call(command, stdout=dev_null, stderr=dev_null)
        else:
            print('Calling command:', ' '.join(command))
            retcode = call(command)
    command = ['make', target]
    if silent:
        with open(devnull, 'w') as dev_null:
            retcode = call(command, stdout=dev_null, stderr=dev_null)
    else:
        print('Calling command:', ' '.join(command))
        retcode = call(command)
    if retcode:
        raise ImportError ('Error compiling '+target)
